apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhbw-weather-backend
spec:
  selector:
    matchLabels:
      app: dhbw-weather
      component: backend
  template:
    metadata:
      labels:
        app: dhbw-weather
        component: backend
    spec:
      containers:
      - name: backend
        image: dhbwreg.azurecr.io/dhbw-demo-docker-backend:v4
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
        ports:
        - containerPort: 80
          name: http
