apiVersion: v1
kind: Service
metadata:
  name: dhbw-weather-backend-service
spec:
  type: ClusterIP
  selector:
    app: dhbw-weather
    component: backend
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  
